#pragma once

#define FIELD_NONE						0x00

#define FIELD_WALL                      0x01
#define FIELD_BLACK_WALL                0x02
#define FIELD_WALL2                     0x03
#define FIELD_FORCE_FIELD_START			0x04
#define FIELD_TYPES_WALLS_END	        FIELD_FORCE_FIELD_START

#define FIELD_FORCE_FIELD_END           0x05
#define FIELD_ROBBO_DRAG_LEFT           0x06
#define FIELD_ROBBO_DRAG_RIGHT          0x07
#define FIELD_SHIP                      0x08
#define FIELD_SHIP_BLINK1               0x09
#define FIELD_SHIP_BLINK2               0x0a
#define FIELD_ROBBO_START               0x0b
#define FIELD_MAGNET_LEFT               0x0c
#define FIELD_MAGNET_RIGHT              0x0d
#define FIELD_PROJECTILE_LEFT           0x0e
#define FIELD_PROJECTILE_RIGHT          0x0f
#define FIELD_PROJECTILE_UP             0x10
#define FIELD_PROJECTILE_DOWN           0x11
#define FIELD_LASER_HEAD_LEFT           0x12
#define FIELD_LASER_HEAD_RIGHT          0x13
#define FIELD_LASER_HEAD_UP             0x14
#define FIELD_LASER_HEAD_DOWN           0x15
#define FIELD_BLASTER_HEAD_LEFT         0x16
#define FIELD_BLASTER_HEAD_RIGHT        0x17
#define FIELD_BLASTER_HEAD_UP           0x18
#define FIELD_BLASTER_HEAD_DOWN         0x19
#define FIELD_BOMB_EXPLODING            0x1a
#define FIELD_PROJECTILE_HORIZONTAL     0x1b
#define FIELD_PROJECTILE_VERTICAL       0x1c
#define FIELD_FORCE_FIELD               0x1d
#define FIELD_ROBBO                     0x1e

#define FIELD_EYES                      0x1f
#define FIELD_MONSTERS_START            FIELD_EYES
#define FIELD_LEFT_HAND_LEFT            0x20
#define FIELD_LEFT_HAND_RIGHT           0x21
#define FIELD_LEFT_HAND_UP              0x22
#define FIELD_LEFT_HAND_DOWN            0x23
#define FIELD_RIGHT_HAND_LEFT           0x24
#define FIELD_RIGHT_HAND_RIGHT          0x25
#define FIELD_RIGHT_HAND_UP             0x26
#define FIELD_RIGHT_HAND_DOWN           0x27
#define FIELD_BAT_LEFT                  0x28
#define FIELD_BAT_RIGHT                 0x29
#define FIELD_BAT_UP                    0x2a
#define FIELD_BAT_DOWN                  0x2b
#define FIELD_BAT_SHOOTING_LEFT         0x2c
#define FIELD_BAT_SHOOTING_RIGHT        0x2d
#define FIELD_MONSTERS_END              FIELD_BAT_SHOOTING_RIGHT
#define FIELD_INERT_BOX_LEFT            0x2e
#define FIELD_INERT_BOX_RIGHT           0x2f
#define FIELD_INERT_BOX_UP              0x30
#define FIELD_INERT_BOX_DOWN            0x31
#define FIELD_SURPRISE_EXPLOSION        0x32
#define FIELD_TELEPORT0                 0x33
#define FIELD_TELEPORT1                 0x34
#define FIELD_TELEPORT2                 0x35
#define FIELD_TELEPORT3                 0x36
#define FIELD_TELEPORT4                 0x37
#define FIELD_TELEPORT5                 0x38
#define FIELD_TELEPORT6                 0x39
#define FIELD_TELEPORT7                 0x3a
#define FIELD_TELEPORT8                 0x3b
#define FIELD_TELEPORT9                 0x3c
#define FIELD_GUN_LEFT                  0x3d
#define FIELD_GUN_RIGHT                 0x3e
#define FIELD_GUN_UP                    0x3f
#define FIELD_GUN_DOWN                  0x40
#define FIELD_LASER_LEFT                0x41
#define FIELD_LASER_RIGHT               0x42
#define FIELD_LASER_UP                  0x43
#define FIELD_LASER_DOWN                0x44
#define FIELD_BLASTER_LEFT              0x45
#define FIELD_BLASTER_RIGHT             0x46
#define FIELD_BLASTER_UP                0x47
#define FIELD_BLASTER_DOWN              0x48
#define FIELD_ROTATING_GUN_LEFT         0x49
#define FIELD_ROTATING_GUN_RIGHT        0x4a
#define FIELD_ROTATING_GUN_UP           0x4b
#define FIELD_ROTATING_GUN_DOWN         0x4c
#define FIELD_MOVABLE_GUN_LEFT          0x4d
#define FIELD_MOVABLE_GUN_RIGHT         0x4e
#define FIELD_EXPLOSION_ANIM1           0x4f
#define FIELD_EXPLOSION_ANIM2           0x50
#define FIELD_EXPLOSION_ANIM3           0x51
#define FIELD_EXPLOSION_ANIM4           0x52
#define FIELD_EXPLOSION_ANIM5           0x53
#define FIELD_EXPLOSION_ANIM6           0x54
#define FIELD_EXPLOSION_ANIM7           0x55
#define FIELD_ROBBO_APEARS_ANIM1        0x56
#define FIELD_ROBBO_APEARS_ANIM2        0x57
#define FIELD_ROBBO_APEARS_ANIM3        0x58
#define FIELD_ROBBO_APEARS_ANIM4        0x59
#define FIELD_ROBBO_APEARS_ANIM5        0x5a
#define FIELD_SURPRISE_SHOOT_ANIM1      0x5b
#define FIELD_SURPRISE_SHOOT_ANIM2      0x5c
#define FIELD_SURPRISE_SHOOT_ANIM3      0x5d
#define FIELD_SURPRISE_SHOOT_ANIM4      0x5e
#define FIELD_SURPRISE_SHOOT_ANIM5      0x5f
#define FIELD_SURPRISE_SHOOT_ANIM6      0x60
#define FIELD_SURPRISE_SHOOT_ANIM7      0x61
#define FIELD_SURPRISE_SHOOT_ANIM8      0x62
#define FIELD_OPENING_DOOR              0x63
#define FIELD_ROBBO_DRAG_ANIM1          0x64
#define FIELD_ROBBO_DRAG_ANIM2          0x65
#define FIELD_SCREW                     0x66
#define FIELD_TYPES_NEXT_START		    FIELD_EXPLOSION_ANIM1
#define FIELD_TYPES_FUNCTIONS_END	    FIELD_SCREW

#define FIELD_KEY                       0x67
#define FIELD_EMPTY                     0x68
#define FIELD_INERT_BOX                 0x69
#define FIELD_DOOR                      0x6a
#define FIELD_BOX                       0x6b
#define FIELD_SURPRISE                  0x6c
#define FIELD_BOMB                      0x6d
#define FIELD_AMMO                      0x6e
#define FIELD_GROUND                    0x6f
#define FIELD_LIFE						0x70
#define FIELD_TYPES_NONE_START		    FIELD_KEY
#define FIELD_TYPES_MAX                 0x7f
#define FIELD_TYPES_WAIT_FLAG           0x80