#pragma once

void forceField();
void forceFieldEnd();
void next();
void blinkOnOdd();
void surpriseExplosion();
void robboDragLeft();
void robboDragRight();
void ship();
void shipBlink1();
void shipBlink2();
void magnetLeft();
void magnetRight();
void inertBoxLeft();
void inertBoxRight();
void inertBoxUp();
void inertBoxDown();
void teleport();
void explode();
void none();