#pragma once

#define	FIELD_NONE					0x00
#define	FIELD_BLASTER_R				0x01
#define	FIELD_BLASTER_L				0x04
#define	FIELD_FORCEFIELD_END		0x05
#define	FIELD_INERT_BOX				0x06
#define	FIELD_MOVABLE_GUN_L			0x0d
#define	FIELD_MOVABLE_GUN_R			0x0e
#define	FIELD_FORCEFIELD			0x0f
#define	FIELD_FORCEFIELD_START		0x11
#define	FIELD_DOOR					0x12
#define	FIELD_BLACK_WALL			0x13
#define	FIELD_SHIP					0x14
#define	FIELD_BLASTER_D				0x17
#define	FIELD_BLASTER_U				0x18
#define	FIELD_GUN_U					0x1c
#define	FIELD_GUN_D					0x1d
#define	FIELD_GUN_L					0x1e
#define	FIELD_GUN_R					0x1f
#define	FIELD_EMPTY					0x20
#define	FIELD_AMMO					0x21
#define	FIELD_BOX					0x23
#define	FIELD_SCREW					0x24
#define	FIELD_GROUND				0x25
#define	FIELD_MONSTER_EYES			0x26
#define	FIELD_LASER_D				0x27
#define	FIELD_MEGNET_R				0x28
#define	FIELD_MAGNET_L				0x29
#define	FIELD_ROBBO					0x2a
#define	FIELD_LIFE					0x2b
#define	FIELD_ROTATING_GUN_R		0x2c
#define	FIELD_ROTATING_GUN_L		0x2d
#define	FIELD_TELEPORT0				0x30
#define	FIELD_TELEPORT1				0x31
#define	FIELD_TELEPORT2				0x32
#define	FIELD_TELEPORT3				0x33
#define	FIELD_TELEPORT4				0x34
#define	FIELD_TELEPORT5				0x35
#define	FIELD_TELEPORT6				0x36
#define	FIELD_TELEPORT7				0x37
#define	FIELD_TELEPORT8				0x38
#define	FIELD_TELEPORT9				0x39
#define	FIELD_LASER_L				0x3c
#define	FIELD_KEY					0x3d
#define	FIELD_LASER_R				0x3e
#define	FIELD_SUPRISE				0x3f
#define	FIELD_BOMB					0x40
#define	FIELD_MONSTER_LEFT_L		0x41 //A
#define	FIELD_MONSTER_LEFT_R		0x42 //B
#define	FIELD_MONSTER_LEFT_U		0x43 //C
#define	FIELD_MONSTER_LEFT_D		0x44 //D
#define	FIELD_MONSTER_RIGHT_L		0x45 //E
#define	FIELD_MONSTER_RIGHT_R		0x46 //F
#define	FIELD_MONSTER_RIGHT_U		0x47 //G
#define	FIELD_MONSTER_RIGHT_D		0x48 //H
#define	FIELD_MONSTER_BIRD_L		0x49 //I
#define	FIELD_MONSTER_BIRD_R		0x4a //J
#define	FIELD_MONSTER_BIRD_U		0x4b //K
#define	FIELD_MONSTER_BIRD_D		0x4c //L
#define	FIELD_MONSTER_SHOOTING_L	0x4d //M
#define	FIELD_MONSTER_SHOOTING_R	0x4e //N
#define	FIELD_PROJECTILE_L			0x4f //O
#define	FIELD_PROJECTILE_R			0x50 //P
#define	FIELD_PROJECTILE_U			0x51 //Q
#define	FIELD_PROJECTILE_D			0x52 //R
#define	FIELD_LASER_BEAM_L			0x53 //S
#define	FIELD_LASER_BEAM_R			0x54 //T
#define	FIELD_LASER_BEAM_U			0x55 //U
#define	FIELD_LASER_BEAM_D			0x56 //V
#define	FIELD_BLASTER_HEAD_L		0x57 //W
#define	FIELD_BLASTER_HEAD_R		0x58 //X
#define	FIELD_BLASTER_HEAD_U		0x59 //Y
#define	FIELD_BLASTER_HEAD_D		0x5a //Z

#define	FIELD_LASER_VERTICAL_RAY	0x5b
#define	FIELD_WALL2					0x5c
#define	FIELD_LASER_HORIZONTAL_RAY	0x5d
#define	FIELD_LASER_U				0x5e

#define FIELD_EXPLOSION1			0x61
#define FIELD_EXPLOSION2			0x62
#define FIELD_EXPLOSION3			0x63
#define FIELD_EXPLOSION4			0x64
#define FIELD_EXPLOSION5			0x65
#define FIELD_EXPLOSION6			0x66
#define FIELD_EXPLOSION7			0x67

#define	FIELD_DOOR2					0x7c
#define	FIELD_WALL					0xa0