#pragma once

#define FIELD_EMPTY ' '
#define FIELD_WALL '!'
#define MOB_R_LEFT '"'
#define MOB_R_RIGHT '#'
#define MOB_R_DOWN '$'
#define MOB_R_UP '%'
#define MOB_L_LEFT '&'
#define MOB_L_RIGHT '\''
#define MOB_L_DOWN '('
#define MOB_L_UP ')'
#define SCREW '*'
#define LASER_HORIZONTAL_HEAD_RIGHT_RIGHT	'+'
#define LASER_HORIZONTAL_RAY				','
#define HORIZONTAL_MISSLE_LEFT				'-'
#define LASER_RIGHT							'.'
#define FIELD_EXPLOSION3					'/'
#define FIELD_EXPLOSION4					'0'
#define GUN_LEFT							'1'
#define FIELD_NONE 0x0