#pragma once

#include "stdbool.h"

bool laserHeadLeft();
bool laserHeadRight();
bool laserHeadUp();
bool laserHeadDown();
bool projectileLeft();
bool projectileRight();
bool projectileUp();
bool projectileDown();
bool laserLeft();
bool laserRight();
bool laserUp();
bool laserDown();
bool gunLeft();
bool gunRight();
bool gunUp();
bool gunDown();
bool blasterHeadLeft();
bool blasterHeadRight();
bool blasterHeadUp();
bool blasterHeadDown();
bool blasterLeft();
bool blasterRight();
bool blasterUp();
bool blasterDown();
bool rotatingGunLeft();
bool rotatingGunRight();
bool rotatingGunUp();
bool rotatingGunDown();
bool movableGunLeft();
bool movableGunRight();