#pragma once

#include "stdbool.h"

bool laserBeamL();
bool laserBeamR();
bool laserBeamU();
bool laserBeamD();
bool projectileL();
bool projectileR();
bool projectileU();
bool projectileD();
bool expolosion();
bool laserL();
bool laserR();
bool laserU();
bool laserD();
bool gunL();
bool gunR();
bool gunU();
bool gunD();
bool blasterHeadL();
bool blasterHeadR();
bool blasterHeadU();
bool blasterHeadD();
bool blasterL();
bool blasterR();
bool blasterU();
bool blasterD();