#include <stdint.h>
#include <tiles.h>
#include <string.h>
#include <map_to_tiles.h>

#pragma bank 255

BANKREF(map_to_tiles_data)

const uint8_t map_to_tiles_data[4][128] = 
{
{
    TILE_EMPTY, TILE_WALL, TILE_BLACK_WALL, TILE_WALL2, TILE_WALL, TILE_WALL, TILE_ROBBO_RIGHT, TILE_ROBBO_LEFT, 
    TILE_SHIP, TILE_SHIP, TILE_SHIP2, TILE_SHIP, TILE_MAGNET_LEFT, TILE_MAGNET_RIGHT, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, 
    TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_EXPLOSION1, TILE_EXPLOSION1, 
    TILE_EXPLOSION1, TILE_EXPLOSION1, TILE_BOMB, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_FORCE_FIELD, TILE_ROBBO_DOWN, TILE_EYES, 
    TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, 
    TILE_BAT, TILE_BAT, TILE_BAT, TILE_BAT, TILE_BAT_SHOOTING, TILE_BAT_SHOOTING, TILE_INERT_BOX, TILE_INERT_BOX, 
    TILE_INERT_BOX, TILE_INERT_BOX, TILE_EMPTY, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, 
    TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_UP2, TILE_GUN_UP2, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_EMPTY, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EMPTY, TILE_EXPLOSION1, TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, 
    TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_DOOR, TILE_SCREW, TILE_KEY, TILE_INERT_BOX, TILE_DOOR, 
    TILE_BOX, TILE_SURPRISE, TILE_BOMB, TILE_AMMO, TILE_GROUND, TILE_LIFE, 
},
{
    TILE_EMPTY, TILE_WALL, TILE_BLACK_WALL, TILE_WALL2, TILE_WALL, TILE_WALL, TILE_ROBBO_RIGHT2, TILE_ROBBO_LEFT2, 
    TILE_SHIP, TILE_SHIP, TILE_SHIP2, TILE_SHIP, TILE_MAGNET_LEFT, TILE_MAGNET_RIGHT, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, 
    TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_EXPLOSION1, TILE_EXPLOSION1, 
    TILE_EXPLOSION1, TILE_EXPLOSION1, TILE_BOMB, TILE_PROJECTILE_HORIZONTAL, TILE_PROJECTILE_VERTICAL, TILE_FORCE_FIELD2, TILE_ROBBO_DOWN, TILE_EYES, 
    TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, 
    TILE_BAT2, TILE_BAT2, TILE_BAT2, TILE_BAT2, TILE_BAT_SHOOTING2, TILE_BAT_SHOOTING2, TILE_INERT_BOX, TILE_INERT_BOX, 
    TILE_INERT_BOX, TILE_INERT_BOX, TILE_EMPTY, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, 
    TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_TELEPORT, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_UP2, TILE_GUN_UP2, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_EMPTY, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EMPTY, TILE_EXPLOSION1, TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, 
    TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_DOOR, TILE_SCREW, TILE_KEY, TILE_INERT_BOX, TILE_DOOR, 
    TILE_BOX, TILE_SURPRISE, TILE_BOMB, TILE_AMMO, TILE_GROUND, TILE_LIFE, 
},
{
    TILE_EMPTY, TILE_WALL, TILE_BLACK_WALL, TILE_WALL2, TILE_WALL, TILE_WALL, TILE_ROBBO_RIGHT, TILE_ROBBO_LEFT, 
    TILE_SHIP, TILE_SHIP, TILE_SHIP2, TILE_SHIP, TILE_MAGNET_LEFT, TILE_MAGNET_RIGHT, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, 
    TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_EXPLOSION1, TILE_EXPLOSION1, 
    TILE_EXPLOSION1, TILE_EXPLOSION1, TILE_BOMB, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_FORCE_FIELD, TILE_ROBBO_DOWN, TILE_EYES2, 
    TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_LEFT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, TILE_RIGHT_HAND, 
    TILE_BAT, TILE_BAT, TILE_BAT, TILE_BAT, TILE_BAT_SHOOTING, TILE_BAT_SHOOTING, TILE_INERT_BOX, TILE_INERT_BOX, 
    TILE_INERT_BOX, TILE_INERT_BOX, TILE_EMPTY, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, 
    TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_UP2, TILE_GUN_UP2, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_EMPTY, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EMPTY, TILE_EXPLOSION1, TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, 
    TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_DOOR, TILE_SCREW, TILE_KEY, TILE_INERT_BOX, TILE_DOOR, 
    TILE_BOX, TILE_SURPRISE, TILE_BOMB, TILE_AMMO, TILE_GROUND, TILE_LIFE, 
},
{
    TILE_EMPTY, TILE_WALL, TILE_BLACK_WALL, TILE_WALL2, TILE_WALL, TILE_WALL, TILE_ROBBO_RIGHT2, TILE_ROBBO_LEFT2, 
    TILE_SHIP, TILE_SHIP, TILE_SHIP2, TILE_SHIP, TILE_MAGNET_LEFT, TILE_MAGNET_RIGHT, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, 
    TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_EXPLOSION1, TILE_EXPLOSION1, 
    TILE_EXPLOSION1, TILE_EXPLOSION1, TILE_BOMB, TILE_PROJECTILE_HORIZONTAL2, TILE_PROJECTILE_VERTICAL2, TILE_FORCE_FIELD2, TILE_ROBBO_DOWN, TILE_EYES2, 
    TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_LEFT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, TILE_RIGHT_HAND2, 
    TILE_BAT2, TILE_BAT2, TILE_BAT2, TILE_BAT2, TILE_BAT_SHOOTING2, TILE_BAT_SHOOTING2, TILE_INERT_BOX, TILE_INERT_BOX, 
    TILE_INERT_BOX, TILE_INERT_BOX, TILE_EMPTY, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, 
    TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_TELEPORT2, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, 
    TILE_GUN_DOWN, TILE_GUN_LEFT, TILE_GUN_UP, TILE_GUN_RIGHT, TILE_GUN_DOWN, TILE_GUN_UP2, TILE_GUN_UP2, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_EMPTY, TILE_EXPLOSION1, 
    TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, TILE_EMPTY, TILE_EXPLOSION1, TILE_EXPLOSION2, TILE_EXPLOSION3, TILE_EXPLOSION4, 
    TILE_EXPLOSION3, TILE_EXPLOSION2, TILE_EXPLOSION1, TILE_DOOR, TILE_SCREW, TILE_KEY, TILE_INERT_BOX, TILE_DOOR, 
    TILE_BOX, TILE_SURPRISE, TILE_BOMB, TILE_AMMO, TILE_GROUND, TILE_LIFE, 
}};

void loadMapToTilesData() BANKED
{
    uint8_t* src = (uint8_t*)(&map_to_tiles_data[0]);
    memcpy(map_to_tiles0, src, 512);
}